### ISSUE TITLE
IO error when reading 32-bit WAV file

### ISSUE THREAD

**Issue by asehgal123** [swharden/Spectrogram#21]
First of all great package, I am definately going to play around with it.

However I am gettting follwing error on line 105 in WavFile.cs

`System.IO.EndOfStreamException: 'Unable to read beyond the end of the stream.'`

By reading the source code it looks like the loop on line 103 goes through to sampleCount which is calculated based on blocksize. For some reason blocksize is being read as 1 (if I set it to 2 then everything works). I am new to this so I don't fully understand the file format.

Wav file that I am loading has channelCount of 1 and blockSize of 1 (Is that even correct? could it be that wav file is incorrect), you think you can take a look at this issue? 

- Abhi

**Comment by swharden** [comment]
Hi @asehgal123, thanks for reporting this! Can you upload the WAV file you're trying to read? My guess is something is weird about the WAV file header. 

An alternative solution is to use a different library (one designed just for reading audio files) to read your WAV file. I think NAudio has a module which can do this.

**Comment by asehgal123** [comment]
Apparently github won't allow me to upload wav file, can I email that to you?

**Comment by swharden** [comment]
Interesting! Perhaps try zipping it, then uploading it?

You're welcome to email it to me too, though if it's too big for email it might not come through

**Comment by asehgal123** [comment]
[sound2.zip](https://github.com/swharden/Spectrogram/files/4997428/sound2.zip)

**Comment by swharden** [comment]
It doubled in size because the original is mono but the converted one is stereo 🤔

Interestingly the source audio is a 32-bit WAV file, and I'm pretty sure that's the core problem here, but I'll work try to get get it supported anyhow. We're making progress here, but it might take another day or two... thanks for uploading these samples! 👍

**Comment by swharden** [comment]
The WAV header claims it's a 16-bit format...

![image](https://user-images.githubusercontent.com/4165489/89088892-aa925e00-d368-11ea-865d-6153a8ad8577.png)

but GoldWave somehow knows its a 32-bit
![image](https://user-images.githubusercontent.com/4165489/89088909-bbdb6a80-d368-11ea-9486-9253af24375f.png)

I want to study spectrograms, not WAV file header byte structure - that problem is solved better elsewhere - so I think my solution for this will to flash a warning message whenever the user tries to use my WAV file reader encouraging them to use another library that's intended for decoding audio file formats.

An intermediate option is I can make a WAV file reading function where the _user_ has to manually define the bit-depth, sample rate, byte format, etc... TBH my only gripe is about reading WAV headers, and the massive inconsistency in how different programs write them 😩

**Comment by swharden** [comment]
@asehgal123 install NAudio then use its `AudioFileReader` like this:

```cs
double[] audio;
int sampleRate;
using (var audioFileReader = new AudioFileReader("asehgal-original.wav"))
{
	sampleRate = audioFileReader.WaveFormat.SampleRate;
	var wholeFile = new List<float>((int)(audioFileReader.Length / 4));
	var readBuffer = new float[audioFileReader.WaveFormat.SampleRate * audioFileReader.WaveFormat.Channels];
	int samplesRead = 0;
	while ((samplesRead = audioFileReader.Read(readBuffer, 0, readBuffer.Length)) > 0)
		wholeFile.AddRange(readBuffer.Take(samplesRead));
	audio = Array.ConvertAll(wholeFile.ToArray(), x => (double)x);
}

int fftSize = 8192;
var spec = new Spectrogram(sampleRate, fftSize, stepSize: 4_000, maxFreq: 2_000);
spec.Add(audio);
spec.SaveImage("asehgal.png", intensity: 10_000, dB: true);
```

The audio file you provided is pretty boring - it's just silence - but the bottom 2kHz of its spectrogram looks like this when you run the code above:

![image](https://user-images.githubusercontent.com/4165489/89089989-10351900-d36e-11ea-937b-d8f7ee5e030e.png)

Hope it helps!

**Comment by asehgal123** [comment]
> ```cs
> 	int samplesRead = 0;
> ```

thanks for your time and help. I will try this out.
