### ISSUE TITLE
Packages with vulnerabilities

### ISSUE THREAD

**Issue by jmcmeen** [swharden/Spectrogram#64]
This package lists System.Drawing.Common >= 4.6.1 as dependency which has a vulnerability. 

Bump version?

![image](https://github.com/user-attachments/assets/b684802e-7d57-4f80-a231-a2a1c7ee44d5)

**Comment by swharden** [comment]
Hi @jmcmeen, will do - thanks!

**Comment by swharden** [comment]
@jmcmeen actually I may walk that statement back -- check out the _preview_ version of Spectrogram. I don't think it has that dependency at all. The upcoming version will use SkiaSharp instead of System.Drawing, so "problem solved" once I publish a version without the prerelease tag 👍 

Let me know if you try the preview version and a hit a similar issue though.

Thanks again for reporting this!
